"""
Django settings for universidad_examenes project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Cargar variables de entorno
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-et-_2h1q^1#q!^m0z7p%%=s0d@ehtwmm8pl#a&e!#eaafyd4eh'
#SECRET_KEY = os.getenv('django-insecure-et-_2h1q^1#q!^m0z7p%%=s0d@ehtwmm8pl#a&e!#eaafyd4eh')
SECRET_KEY = os.getenv('SECRET_KEY') # <-- ¡ASÍ ES CORRECTO!

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = os.getenv('DEBUG', 'False') == 'True'


#ALLOWED_HOSTS = []
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  ######
    'django.middleware.common.CommonMiddleware',



    # --- ¡ESTAS DOS LÍNEAS DEBEN INVERTIRSE! ---
    'django.contrib.auth.middleware.AuthenticationMiddleware', # <-- PON ESTA PRIMERO
    'django.middleware.csrf.CsrfViewMiddleware', # <-- PON ESTA SEGUNDO
    # --- FIN DEL CAMBIO ---


    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'universidad_examenes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'universidad_examenes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'universidad',           # tu base
        'USER': 'root',                # tu usuario MySQL
        'PASSWORD': 'root',        # tu contraseña
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ... (al final de tu settings.py) ...

# Esto le dice a django-cors-headers que permita la llamada
CORS_ALLOWED_ORIGINS = [
    "chrome-extension://dkoapjjnbnhkefaldbmmobfgibepjjja"
]
CORS_ALLOW_CREDENTIALS = True

# --- ¡ESTA ES LA LÍNEA QUE FALTABA! ---
# Esto le dice al CsrfViewMiddleware de Django que confíe en la extensión
CSRF_TRUSTED_ORIGINS = [
    "chrome-extension://dkoapjjnbnhkefaldbmmobfgibepjjja"
]