# Generated by Django 5.2.8 on 2025-11-17 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_cursos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=255)),
                ('id_profesor', models.ForeignKey(blank=True, db_column='id_profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.cursos')),
            ],
            options={
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='PreguntasExamen',
            fields=[
                ('id_preguntas_examen', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('id_examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.examen')),
            ],
            options={
                'db_table': 'preguntas_examen',
            },
        ),
        migrations.CreateModel(
            name='AlternativasExamen',
            fields=[
                ('id_alternativas_examen', models.AutoField(primary_key=True, serialize=False)),
                ('texto_alternativa', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=1)),
                ('id_preguntas_examen', models.ForeignKey(db_column='id_preguntas_examen', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.preguntasexamen')),
            ],
            options={
                'db_table': 'alternativas_examen',
            },
        ),
        migrations.CreateModel(
            name='EstadoExamen',
            fields=[
                ('id_estado_examen', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.examen')),
            ],
            options={
                'db_table': 'estado_examen',
                'constraints': [models.UniqueConstraint(fields=('user', 'id_examen'), name='unique_user_exam_status')],
            },
        ),
        migrations.CreateModel(
            name='RespuestasUsuario',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('id_alternativas_examen', models.ForeignKey(db_column='id_alternativas_examen', on_delete=django.db.models.deletion.CASCADE, to='tasks.alternativasexamen')),
                ('id_examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, to='tasks.examen')),
                ('id_preguntas_examen', models.ForeignKey(db_column='id_preguntas_examen', on_delete=django.db.models.deletion.CASCADE, to='tasks.preguntasexamen')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respuestas_usuario',
                'constraints': [models.UniqueConstraint(fields=('user', 'id_examen', 'id_preguntas_examen'), name='respuesta_unica_por_pregunta')],
            },
        ),
    ]
