# Generated by Django 5.2.8 on 2025-11-17 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cursos_examen_preguntasexamen_alternativasexamen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id_salon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_salon', models.CharField(max_length=100)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, related_name='salones_asociados', to='tasks.cursos')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='salones_gestionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salon',
            },
        ),
        migrations.CreateModel(
            name='SalonAlumnos',
            fields=[
                ('id_salonalumno', models.AutoField(primary_key=True, serialize=False)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_salon', models.ForeignKey(db_column='id_salon', on_delete=django.db.models.deletion.CASCADE, to='tasks.salon')),
            ],
            options={
                'db_table': 'salon_alumnos',
                'unique_together': {('id_salon', 'id_alumno')},
            },
        ),
        migrations.AddField(
            model_name='salon',
            name='alumnos',
            field=models.ManyToManyField(related_name='salones_inscritos', through='tasks.SalonAlumnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
