# Generated by Django 5.2.8 on 2025-11-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_salon_salonalumnos_salon_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativasexamen',
            name='texto_alternativa',
            field=models.TextField(),
        ),
    ]
