# Generated by Django 5.2.8 on 2025-11-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_alternativasexamen_texto_alternativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasexamen',
            name='texto_pregunta',
            field=models.TextField(),
        ),
    ]
