# Generated by Django 5.2.8 on 2025-11-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_preguntasexamen_texto_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='cantidad_preguntas',
            field=models.IntegerField(default=0, help_text='Cantidad de preguntas aleatorias a mostrar. 0 para mostrar todas.'),
        ),
    ]
